### ISSUE TITLE
Requesting feedback on simpler, mobile-friendly version

### ISSUE THREAD

**Issue by ChasKane** [pjeby/hot-reload#19]
I have this reloading my plugin-in-development on save on both desktop and mobile. This relies on the `vault.on('raw')` listener which I discovered from your code. When I saw that it worked the same on mobile, I had to give this a try. This implementation could use some debouncing, a settings panel, and your `.hotreload`/`.git` trick, but otherwise it seems much simpler than also using a watcher like you did, and it works on mobile.

In the README you mention @shabegom 's [Hot Reload Mobile](https://github.com/shabegom/obsidian-hot-reload-mobile), which didn't work for me, so I think this might hit 2 birds with 1 stone? Lmk what you think :)

```js
const { Plugin } = require('obsidian');

module.exports = class MobileHotReload extends Plugin {
    pluginReloader(file) {
	const pluginsDir = app.plugins.getPluginFolder() + '/';
	if(file && file.startsWith(pluginsDir) && ['manifest.json', 'main.js', 'styles.css'].some(s => file.includes(s))) {
            let fileDir = file.substring(pluginsDir.length);
            fileDir = fileDir.substring(0, fileDir.indexOf('/'));
            Object.values(app.plugins.plugins).map(plugin => {
		if((pluginsDir + fileDir) === plugin.manifest.dir) {
	            console.log('HOT RELOAD 🔥 🏁 restarting plugin: ' + plugin.manifest.id)
	            app.plugins.disablePlugin(plugin.manifest.id)
	            app.plugins.enablePlugin(plugin.manifest.id)
                }
            })
	}
    }

    onload() {
	app.vault.on('raw', this.pluginReloader)
    }

    onunload() {
	this.app.vault.offref(this.pluginReloader)
    }

}
```

**Comment by pjeby** [comment]
The reason I use a watcher is because on Linux, at least with older versions of Obsidian, Obsidian did not add watches for plugin folders, and the watchers it used were not recursive.  So without the additional watchers, hot reload just didn't work on Linux.  And since Android is based on Linux, I assumed it wouldn't work there either.  

The code you posted also contains some significant errors, for example, the load/unload methods are quite broken.  They should be written:

```ts
    onload() {
	app.vault.on('raw', this.pluginReloader, this)
    }

    onunload() {
	this.app.vault.off('raw', this.pluginReloader)
    }
```

Or more simply:

```ts
    onload() {
	this.registerEvent(this.app.vault.on('raw', this.pluginReloader, this))
    }

    // no onunload() method needed
```

In any case, for Linux and mobile I could get rid of the Node.js requirement (because the watch is always needed), but for Windows and Mac I need the symlink check, unless Obsidian has been changed to handle recursive watching in such cases.

In short, changing hot-reload to get rid of the `fs` dependency entirely or stop using extra watches would be somewhat tricky.  I can think of a way it could be done, though, which is to only check for the existence of symlinks (and require `fs`) when running on desktop platforms, and to assume on other platforms that the watches are required without checking.  The directory-checking stat can also be replaced with vault.adapter.stat(), which wasn't available when I first wrote hot-reload.

So I think I can try making hot-reload mobile-compatible like that, but it's unclear to me whether that would actually work properly, especially without Sync.  It'd probably look something like:

```ts
    watch(path) {
        if (this.app.vault.adapter.watchers.hasOwnProperty(path)) return;
        if (this.app.vault.adapter.stat(path).type !== "folder") return;
        if (watchNeeded || this.isSymlink(path)) this.app.vault.adapter.startWatchPath(path, false);
    }

    isSymlink = (() => {
        try {
            const fs = require('fs');
            return path => {
                const realPath = [this.app.vault.adapter.basePath, path].join("/");
                const lstat = fs.lstatSync(realPath, {throwIfNoEntry: false});
                return lstat && lstat.isSymbolicLink();
            }
        } catch (e) {
            return () => true;
        }
    });
```

This should let the plugin be imported on mobile, while not changing its behavior elsewhere.  (The only downside being that it would create watches for every single plugin folder on mobile, with unknown impact on performance.)

**Comment by pjeby** [comment]
I've now pushed the above as 0.1.12, if you want to try it.

**Comment by ChasKane** [comment]
Thanks so much for your thoughts -- I learned a ton from this, chiefly that the skill tree is much taller than I realized heheh. I'm moving around a lot rn but will compare your implementation to mine (which has been working for my use case), hopefully in November ^.^
