### ISSUE TITLE
Hot Reload not Working on File Replacement

### ISSUE THREAD

**Issue by LennardZuendorf** [pjeby/hot-reload#21]
Hey, I've been struggling with hot reload during my plugin development:

I'm not 100% sure but I think it's because my esbuild and tailwind CLI workflow replacing replacing the files in the plugin folder instead of updating it. Again, not definitely the problem, but it's not working and it used to work before I changed some things in the build process and now also have the vault in a subfolder of my repo.

I've done some research on this and what do you think about using hashes of the files to compare if there's a change? This should be 100% safe even if files are replaced right? Otherwise, if you don't think it's the file replacement, it would be great if you could point me in the direction of another idea as to why this isn't working for me at the moment.

Have been really enjoying the plugin otherwise, it makes development significantly easier!

**Comment by pjeby** [comment]
If you use the "Hot Reload: Check plugins for changes and reload them" command, does the plugin reload?

**Comment by LennardZuendorf** [comment]
Hey!

No it wasn't reloading at all. Also after running the scan command manually.

But I think this was because of my folder structure where I had the obsidian vault within my repo and not the other way around (as it's suggested by obsidian). With a slightly adjusted build config I got a read only file system error, which leads me to think it was something with that.

I redid my build config now, moved the vault back and it works perfectly again. So I guess the takeaway is that the setup was probably just wrong.

I'll go ahead and close the issue, thank you for the quick reaction!

**Comment by pjeby** [comment]
One thing you can do, by the way, if you don't want your git repo inside Obsidian, is to make your dist or build folder (wherever your builder puts it files) a symlink to a subdirectory of the vault's `.obsidian/plugins` folder.  I find this is easiest when building plugins that don't use the [ophidian-lib/build](https://github.com/ophidian-lib/build) library.  (Which doesn't need the symlink because you can just give it an environment variable pointing to the vault you want to send your builds to.)

**Comment by LennardZuendorf** [comment]
Oh right I didn't think of that...

And I'll definitely check out ophidian, it looks great already at first glance!
